version: "3.9"
services:
  api:
    build: .
    ports: ["8080:8080"]
    environment:
      DB_DSN: postgres://short:secret@db:5432/shortlink?sslmode=disable
      PORT: 8080
      LOG_LEVEL: DEBUG
    depends_on: [db]

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: shortlink
      POSTGRES_USER: short
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports: ["5432:5432"]

volumes:
  pgdata:
